spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # register center address
server: 
  port: 8083
zuul:
  routes:
    service0: /service0/**
    service1: /service1/**